### ISSUE TITLE
Enhancement Request - Add the ability to update start position and rotation position

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/parcel-drafter#78]
Currently, the Parcel Drafter allows you to move a parcel in edit mode by clicking on the map and the start position updates.  

Users have requested that something visual on the Parcel indicating where the start position is and allow them to snap it to another position on the parcel.  This new position would be used to update the placement and rotation of the parcel.

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

As discussed we will work on getting some designs and solutions to implement this requirement and share it with you.

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

## Requirement 1: Highlight the start point
- We can add symbol selector in configuration settings to select the symbol which will be used for highlighting the start point.
![image](https://user-images.githubusercontent.com/2959186/38977247-6f2291ec-43d1-11e8-8157-68e50f6f176a.png)

___


## Requirement 2: Allow user to update the rotation point

- We discussed an approach of allowing user to drag the start point similar to ArcMap. However , we checked its feasibility and it looks we need to do major code changes to incorporate the feature of dragging rotation point.
- So we recommend the following approach:
  - Add "Update rotation point" tool in the widget panel
     ![image](https://user-images.githubusercontent.com/2959186/38977520-3eefcbec-43d2-11e8-88a3-1ecdd6c68d89.png)
  - Once the tool is activated user can see the current rotation point on map _(Rotation point symbol is show in pink circle)_:
     ![image](https://user-images.githubusercontent.com/2959186/38977604-76178376-43d2-11e8-9c3e-59e95e4f130e.png)
  - Also map tool-tip will be updated to say "Click to update rotation point"
![image](https://user-images.githubusercontent.com/2959186/38977832-28b64aa8-43d3-11e8-845c-92ceadaef849.png)
   - When this tool is active user can click on any of the points which are already added(shown in red) to make it as a point of rotation
   - Once user click on the point it will be used for rotation
![image](https://user-images.githubusercontent.com/2959186/38977955-84ae7ccc-43d3-11e8-815c-e288b433db2d.png)

   - If any traverse info is Modified(Angle/Length/Radius), Deleted, Rearranged(By dragging the rows in table) the rotation point will be shifted back to "Start Point".

   - Also, we cannot maintain the updated rotation point when user is opening the parcel in edit mode. 
___

We have few questions related to this ticket:
 1. Like "Start point symbol" do we have to make the "Rotation point symbol" configurable to user. _(In above screen shots rotation point symbol is show in pink circle)_
 2. The rotation point symbol should be visible all the time or only when "Update rotation point" tool is active.

Please let us know your thoughts on this to finalize the requirement and estimates.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam I agree with the approach.

As for the questions - 

 I don't think that we need to have a specific rotation symbol configurable, can't we just use the start point symbol as the rotation symbol?  Call it the **Start and Rotate Point Symbol**?  When you enable the new **Click to update rotation point** you can click and move it around.  

Reasoning - The start point symbol is purely graphical, the lines in the grid will never get re-ordered if you move the point, just the graphic on screen will get updated and rotated.

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

Yes, we can use only one symbol to represent the start/rotation point.

Please confirm if we need to show both the start and rotation point when they are different.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam I don't think that it's mandatory that we display the start position as different.  Since the user cannot do anything to update it.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam  The new "start point" symbol is overposting on the snap cursor.  Can we please update so that we can see the cross-hair snap symbol on top of the start/rotation point?

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

>@CTLocalGovTeam The new "start point" symbol is overposting on the snap cursor. Can we please update so that we can see the cross-hair snap symbol on top of the start/rotation point?

The cross-hair symbol is on top of rotation point symbol it is not visible due the color, if the color of rotation point symbol is green/cyan then it is not visible. We updated the rotation point symbol in configuration and here is the result.
![78symbol](https://user-images.githubusercontent.com/2959186/40100825-0169b436-5903-11e8-9c65-38860c83e1ff.gif)

___



>@CTLocalGovTeam The new start point doesn't update it's position when using the scale tool.


We have fixed this issue on our side and we will deliver it in next code drop.
![78scale](https://user-images.githubusercontent.com/2959186/40100910-51a7f836-5903-11e8-8056-54ad9ebdd56d.gif)

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam I've noticed when updating the start positing after performing a angle update,  the angle gets thrown away.

![a836face-9d1f-4457-8925-114ab6c42355](https://user-images.githubusercontent.com/5614261/40190437-cec010a0-59b3-11e8-8ce1-e018fa34bb34.GIF)

This is not desirable.

I also noticed the angle in the dialog remains - so there is a mis-match between the rotation in the map.

@CTLocalGovTeam Please also look at the very erratic rotation behavior when you update the rotation position.  It seems that when using the interactive (map) angle click-and-drag, the rotation is based on the new point, but the "handle" hasn't been updated and causes some difficult maneuverability.  Have you seen this?

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

We have updated logic to calculate the angles after rotation point is changed and interactive (map) angle click-and-drag tool is used, this will be delivered in today's code drop. Please check the behavior after today's code drop and let us know your feedback.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam please look at this - when updating the start positing after performing a angle update, the angle gets thrown away.  This is still an issue.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam Retested - verified fixed!

**Comment by ChrisBuscaglia** [comment]
![image](https://user-images.githubusercontent.com/5614261/40437460-05c20f56-5e7b-11e8-8005-9edcf8f31e0f.png)

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

- We have not updated the code to apply/remove angles after updating a start point.
- After start point is changed the existing applied angles will be maintained in both the places (map and widget panel), this was the behavior of existing widget. 
- Also, notice image '1' and image '4' is not same. In image rotation of -180 is not applied whereas in image '4'  rotation is applied  and hence the start point is reflected at bottom right.

![image](https://user-images.githubusercontent.com/2959186/40528182-942efbd0-600d-11e8-8301-ce01828a57f8.png)

Please let us know if we are missing anything.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam we need to visit this on wed. morning.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam Thanks for the hard work and responsiveness on this - change looks good.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam I noticed a minor issue.  When rotating a parcel after changing the rotation point, the map extent doesn't stay "locked" and seems to jump around.  This seems to happen when the parcel is rotated near the edge of the map extent.  Is there a way to lock the extent when you are in the rotate mode?

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

- We cannot completely lock the extent when rotating as we set the extent to parcel lines so that the complete parcel should be visible in current extent.
- We have a functionality to set the extent of the map to the drawn parcel lines.
- Whenever the new entry is added or deleted or parcel is scaled/rotated and if the parcel is not completely visible in current extent then we set the map extent to the drawn parcel lines.
- So, when you are rotating parcel and if it is not completely visible in current extent the above functionality to set the map extent to parcel line gets kicked in and as rotation of parcel event is fired multiple times when using 'Drag to Rotate tool' and it seems like a jump around behavior on map.
- We have updated the code so that this event should not be fired multiple times and here is behavior after implementation.
![pd](https://user-images.githubusercontent.com/2959186/41758753-5bf338a6-7608-11e8-9a15-6aea9eb05ced.gif)

 - We have also shared the applink for your testing in an email.

Please let us know if this looks good.
